import React from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Terms() {
  return (
    <div style={{ background: '#050505', minHeight: '100vh' }}>
      <Navbar />
      <div className="pt-24 max-w-3xl mx-auto px-4 pb-20">
        <h1 className="text-3xl font-playfair font-black text-white mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-8">Last updated: January 1, 2025</p>
        <div className="prose prose-invert prose-sm max-w-none text-gray-300 leading-relaxed space-y-6">
          <section>
            <h2 className="text-lg font-bold text-white mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using LitigationSpace ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>
          <section>
            <h2 className="text-lg font-bold text-white mb-2">2. Description of Service</h2>
            <p>LitigationSpace provides AI-powered legal tools including case management, document drafting, legal research, and expert matching services. The Service is not a law firm and does not provide legal advice.</p>
          </section>
          <section>
            <h2 className="text-lg font-bold text-white mb-2">3. No Legal Advice</h2>
            <p>The AI outputs, analyses, and content generated by LitigationSpace are for informational and productivity purposes only. They do not constitute legal advice. Always consult a licensed attorney for legal decisions.</p>
          </section>
          <section>
            <h2 className="text-lg font-bold text-white mb-2">4. Account Responsibilities</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. Notify us immediately of any unauthorized access.</p>
          </section>
          <section>
            <h2 className="text-lg font-bold text-white mb-2">5. Acceptable Use</h2>
            <p>You may not use the Service to engage in illegal activities, upload malicious content, attempt to reverse-engineer our systems, or violate any applicable laws or regulations.</p>
          </section>
          <section>
            <h2 className="text-lg font-bold text-white mb-2">6. Intellectual Property</h2>
            <p>You retain ownership of content you upload. You grant LitigationSpace a limited license to process your content to provide the Service. LitigationSpace retains all rights to its software, designs, and systems.</p>
          </section>
          <section>
            <h2 className="text-lg font-bold text-white mb-2">7. Limitation of Liability</h2>
            <p>LitigationSpace shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, to the maximum extent permitted by law.</p>
          </section>
          <section>
            <h2 className="text-lg font-bold text-white mb-2">8. Contact</h2>
            <p>For questions about these Terms, contact us at legal@litigationspace.com.</p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  )
}
